FROM ubuntu:${UBUNTU_VERSION:-18.04}

ARG BUILD_DATE
ARG BUILD_VERSION
ARG GIT_COMMIT
ARG GIT_URL

ENV VENDOR="DevOpsCornerId"
ENV AUTHOR="DevOpsCorner.id <support@devopscorner.id>"
ENV IMG_NAME="openfortivpn"
ENV IMG_VERSION="18.04"
ENV IMG_DESC="Docker Image OpenFortiVPN from Ubuntu 18.04"
ENV IMG_ARCH="amd64/x86_64"

ENV UBUNTU_VERSION="18.04"
ENV OPENFORTIVPN_VERSION="1.19.0"

LABEL maintainer="$AUTHOR" \
      architecture="$IMG_ARCH" \
      ubuntu-version="$UBUNTU_VERSION" \
      openfortivpn-version="$OPENFORTIVPN_VERSION" \
      org.label-schema.build-date="$BUILD_DATE" \
      org.label-schema.name="$IMG_NAME" \
      org.label-schema.description="$IMG_DESC" \
      org.label-schema.vcs-ref="$GIT_COMMIT" \
      org.label-schema.vcs-url="$GIT_URL" \
      org.label-schema.vendor="$VENDOR" \
      org.label-schema.version="$BUILD_VERSION" \
      org.label-schema.schema-version="$IMG_VERSION" \
      org.opencontainers.image.authors="$AUTHOR" \
      org.opencontainers.image.description="$IMG_DESC" \
      org.opencontainers.image.vendor="$VENDOR" \
      org.opencontainers.image.version="$IMG_VERSION" \
      org.opencontainers.image.revision="$GIT_COMMIT" \
      org.opencontainers.image.created="$BUILD_DATE" \
      fr.hbis.docker.base.build-date="$BUILD_DATE" \
      fr.hbis.docker.base.name="$IMG_NAME" \
      fr.hbis.docker.base.vendor="$VENDOR" \
      fr.hbis.docker.base.version="$BUILD_VERSION"

ENV DEBIAN_FRONTEND noninteractive

ENV VPN_HOST host
ENV VPN_PORT port
ENV VPN_ADDR host:port
ENV VPN_USER user@domain
ENV VPN_PASS secret
ENV VPN_TRUST_CERT 1234567890987654321
ENV VPN_TIMEOUT 10

USER root
RUN apt -o APT::Sandbox::User=root update; sync
RUN apt-get update; sync
RUN apt-get install -y \
      git \
      bash \
      curl \
      wget \
      apt-transport-https \
      ca-certificates \
      openssh-server \
      openssh-client \
      net-tools \
      expect \
      iproute2 \
      iptables \
      openfortivpn \
      gettext-base \
      network-manager-fortisslvpn \
      iputils-ping; sync

COPY rootfs /
RUN chmod +x /tmp/*.sh; sync

# Copy runfiles
COPY rootfs/tmp/start.sh /start.sh

RUN apt-get clean -q && apt-get autoremove --purge; sync

WORKDIR /root

CMD [ "/start.sh" ]

EXPOSE 22
