---
- include: uninstall.yml

- name: Get nvm installation script
  shell: >
    curl -o- https://raw.githubusercontent.com/creationix/nvm/v{{nvm_version}}/install.sh | bash
  args:
    creates: "{{ ansible_env.HOME }}/.nvm/nvm.sh"

- name: Setup environment nvm
  template: src="{{ item }}.sh.j2" dest=/etc/profile.d/{{item}}.sh
  with_items:
    - nvm

- name: Setup bashrc configuration
  copy: src="{{ item }}" dest="~/.{{item}}"
  with_items:
    - bashrc

- name: Reload bashrc
  shell: /bin/bash -c "source ~/.nvm/nvm.sh"

- name: Copy installation script
  copy: src="{{ item }}.sh" dest="/tmp/{{ item }}.sh"
  with_items:
    - install

- name: Install node ver-{{node_version}}
  shell: bash /tmp/{{ item }}.sh {{node_version}}
  with_items:
    - install

# - name: Setup default node
#   shell: nvm alias default {{ node_version}}
#
# - name: Activate node
#   shell: nvm use {{ node_version }}

- name: Copy symlink node ver-{{node_version}}
  copy: src="{{ item }}.sh" dest="/tmp/{{ item }}.sh"
  with_items:
    - symlink

- name: Symlink node ver-{{node_version}}
  shell: bash /tmp/{{ item }}.sh {{node_version}}
  with_items:
    - symlink
