---
enable_vm_overcommit_memory: False
enable_sysctl_tuning: False
sysctl_settings:
  - name: vm.swappiness
    value: 1
  - name: fs.file-max
    value: 2061677
  - name: fs.nr_open
    value: 2061677
  - name: kernel.pid_max
    value: 4194303
  - name: net.ipv6.conf.all.disable_ipv6
    value: 1
  - name: net.ipv6.conf.default.disable_ipv6
    value: 1
  - name: net.ipv6.conf.lo.disable_ipv6
    value: 1
  - name: net.ipv4.ip_local_port_range
    value: 1024 65535
  - name: net.ipv4.tcp_tw_reuse
    value: 0
  - name: net.core.netdev_max_backlog
    value: 2500
  - name: net.ipv4.tcp_max_tw_buckets
    value: 4123354
  - name: net.core.rmem_default
    value: 16777216
  - name: net.core.wmem_default
    value: 16777216
  - name: net.core.rmem_max
    value: 16777216
  - name: net.core.wmem_max
    value: 16777216
  - name: net.ipv4.tcp_rmem
    value: 4096 87380 16777216
  - name: net.ipv4.tcp_wmem
    value: 4096 65536 16777216
  - name: net.core.somaxconn
    value: 65535
  - name: net.ipv4.tcp_max_syn_backlog
    value: 20000
  - name: net.ipv4.tcp_tw_recycle
    value: 1
  - name: net.ipv4.tcp_congestion_control
    value: cubic
  - name: vm.max_map_count
    value: "{{ ansible_memtotal_mb*8 }}"
