---
dependency:
  name: galaxy

driver:
  name: docker

provisioner:
  name: ansible
  # log: true

verifier:
  name: ansible

scenario:
  name: ubuntu-16.04

platforms:
  - name: ubuntu-16.04
    image: ubuntu:16.04
