- name: Update cache & Full system update
  apt:
    update_cache: true
    upgrade: dist
    cache_valid_time: 3600
    force_apt_get: true

- name: Install Python3
  apt:
    name:
      - python3-minimal
      - python3-pip
    state: present

# - name: Upgrade pip
#   pip:
#     name: pip
#     extra_args: --upgrade
#     executable: pip3

- name: Install Zip Unzip
  apt:
    name:
      - zip
      - unzip
    state: present

- name: Upgrade pip to ver-21.3.1
  shell: "python3 -m pip install pip==21.3.1"
