---
galaxy_info:
  author: Andrew Rothstein
  description: installs kubectl to /usr/local/bin
  company: BlackRock
  license:
    - MIT
  min_ansible_version: 2.0
  platforms:
    - name: Alpine
      versions:
        - all
    - name: Debian
      versions:
        - bullseye
        - buster
    - name: EL
      versions:
        - 8
    - name: Fedora
      versions:
        - 34
    - name: MacOSX
      versions:
        - all
    - name: Ubuntu
      versions:
        - bionic
        - focal
  galaxy_tags:
    - k8s
    - kubernetes
    - cloud
  role_name: kubectl

dependencies: []
