---
- name: Converge
  hosts: all
  become: true

  vars:
    adminer_install_dir: /opt/adminer
    adminer_add_apache_config: false

  pre_tasks:
    - name: Update apt cache.
      apt: update_cache=yes cache_valid_time=600
      when: ansible_os_family == 'Debian'
      changed_when: false

  roles:
    - role: geerlingguy.adminer
