---
- name: Install Jenkins
  hosts: "{{ deploy_hosts }}"
  remote_user: "{{ remote_user | default('ubuntu') }}"
  become: yes

  vars:
    app_name: jenkins
    jenkins_hostname: "{{ jenkins_hostname | default('electramobilitas.id') }}"
    jenkins_http_port: 8080
    java_packages: "{{ java_packages | default('openjdk-11-jdk') }}"
    jenkins_admin_username: "{{ jenkins_admin_username | default('admin') }}"
    jenkins_admin_password: "{{ jenkins_admin_password | default('password') }}"
    jenkins_admin_password_file: "$JENKINS_HOME/secrets/initialAdminPassword"

  roles:
    - ansible-pretasks
    - python-pip
    - java
    - jenkins
