---
- name: Setup Jenkins Worker
  hosts: "{{ deploy_hosts | default('jenkins-master') }}"
  remote_user: "{{ remote_user | default('ubuntu') }}"
  become: yes

  tasks:
    - name: Include Cluster Vars
      include_vars:
        file: "../../services/jenkins/ansible/inventory/{{ env }}/group_vars/metadata_jenkins_master.yaml"

  roles:
    - ansible-pretasks
    - python-pip
    - { role: docker, tags: ["docker"] }
    - { role: java, tags: ["java"] }
    - { role: jenkins, tags: ["jenkins"] }
    - { role: golang, tags: ["golang"] }
    - { role: golang-protobuf, tags: ["golang-protobuf"] }
    - { role: nvm, tags: ["nvm"] }
    - { role: kubectl, tags: ["kubectl"] }
    - { role: aws-cli, tags: ["aws-cli"] }
    - { role: helm, tags: ["helm"] }
    - { role: helmfile, tags: ["helmfile"] }
