---
- name: Setup Jenkins Master
  hosts: "{{ deploy_hosts | default('jenkins-master') }}"
  remote_user: "{{ remote_user | default('ubuntu') }}"
  become: yes

  vars:
    app_name: jenkins-master

    ### Docker ###
    docker_edition:    ce
    docker_channel:    ["stable"]
    docker_version:    "20.10.21"
    docker_compose_version: "2.12.2"

    ### GO ###
    golang_version:    "1.16.10"

    ### Protobuf ###
    protoc_ver:        "3.15.6"

    ### Jenkins ###
    java_home:         "/usr/lib/jvm"
    jenkins_version:   "2.320"
    jenkins_hostname:  "devopscorner.id"
    jenkins_http_port: 8080
    java_packages:     "openjdk-11-jdk"
    jenkins_admin_username: "{{ jenkins_admin_username | default('admin') }}"
    jenkins_admin_password: "{{ jenkins_admin_password | default('password') }}"
    jenkins_admin_password_file: "$JENKINS_HOME/secrets/initialAdminPassword"

    ### NVM ###
    node_version: "16.13.0"

    ### kubectl ###
    kubectl_ver:  "v1.22.2"
    kubectl_platform:  amd64
    kubectl_mirror:    "https://storage.googleapis.com/kubernetes-release/release"
    kubectl_install_dir: "/usr/local/bin"
    kubectl_privilege_escalate: True

  roles:
    - ansible-pretasks
    - python-pip
    - { role: docker, tags: ["docker"] }
    - { role: java, tags: ["java"] }
    - { role: jenkins, tags: ["jenkins"] }
    - { role: golang, tags: ["golang"] }
    - { role: golang-protobuf, tags: ["golang-protobuf"] }
    - { role: nvm, tags: ["nvm"] }
    - { role: kubectl, tags: ["kubectl"] }
    - { role: aws-cli, tags: ["aws-cli"] }
    - { role: helm, tags: ["helm"] }
    - { role: helmfile, tags: ["helmfile"] }
