---
# handlers file for nifi

- name: reload systemd
  systemd:
    daemon_reload: yes
  when: >
    (ansible_distribution == "CentOS" or ansible_distribution == "Red Hat Enterprise Linux") and
    ansible_distribution_major_version >= "7"

- name: restart nifi
  service: name=nifi state=restarted enabled=yes
  when: nifi_perform_restart
