---
galaxy_info:
  role_name: awscli
  author: Christian González Di Antonio
  description: Ansible Role for AWS Command Line Interface (awscli)
  issue_tracker_url: https://github.com/christiangda/ansible-role-awscli
  license: license GPLv3
  company: No Company
  min_ansible_version: 2.9

  platforms:
    - name: EL
      versions:
        - 7
        - 8
    - name: Debian
      versions:
        - stretch
        - buster
        - bullseye
    - name: Ubuntu
      version:
        - xenial
        - bionic
        - focal
        - hirsute

  galaxy_tags:
    - aws
    - tool
    - redhat
    - system
    - utilities
    - amazon
    - linux
    - ubuntu
    - debian
    - centos
    - cloud
    - cli
    - metrics
    - command
    - awscli

dependencies: []
