---
- name: Clean up useless packages from the cache
  command: apt-get clean
  become: yes

- name: Remove useless packages from the cache
  apt:
    autoclean: yes

- name: Remove dependencies that are no longer required
  apt:
    autoremove: yes